# Generated by Django 5.0.6 on 2024-07-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_afetr_sale',
            field=models.IntegerField(default=0),
        ),
    ]
